import { Product } from './types/Product';

export const sampleProducts: Product[] = [
  {
    name: 'Nike Slim shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../images/p1.jpg',
    price: 78,
    countInStock: 20,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Adidas Slim shirt',
    slug: 'adidas-slim-shirt',
    category: 'Shirts',
    image: '../images/p2.jpg',
    price: 120,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Adidas Fit shirt',
    slug: 'adidas-fit-shirt',
    category: 'Shirts',
    image: '../images/p3.jpg',
    price: 150,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Lacoste Free Pants',
    slug: 'lacoste-free-pants',
    category: 'Pants',
    image: '../images/p4.jpg',
    price: 220,
    countInStock: 20,
    brand: 'Lacoste',
    rating: 4.0,
    numReviews: 10,
    description: 'high quality shirt',
  },
];
